# Generated by Django 3.1.3 on 2020-12-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='working',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default='l', max_length=60, unique=True)),
                ('bio', models.CharField(default='', max_length=100)),
                ('telephone', models.IntegerField()),
                ('car_type', models.CharField(choices=[('ركشه', 'ركشه'), ('هايس', 'هايس'), ('موتر', 'موتر'), ('عربيه خاصه', 'عربيه خاصه')], default='1', max_length=12)),
                ('your_picture', models.ImageField(default='profile_pictures/default.jpg', upload_to='profile_pictures/')),
                ('number_picture', models.ImageField(default='profile_pictures/default.jpg', upload_to='profile_pictures/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
